version: '3'

services:
  php:
    image: phpunit/phpunit:latest
    user: "1000"
    volumes:
      - ./src:/srv/html
    working_dir: /srv/html
    entrypoint: ["/bin/sh", "-c", "composer install
      && vendor/phpunit/phpunit/phpunit /srv/html/tests --coverage-html ./coverage"]
  webserver:
    image: nginx:1.15.8
    # Normally I'd create a custom config, but this will do fine
    volumes:
      - ./src/coverage:/usr/share/nginx/html
    working_dir: /srv/html
    ports:
      - "80:80"
    restart: always